#!/usr/bin/env sh

# Terminate already running bar instances
# killall -q polybar
# If all your bars have ipc enabled, you can also use 
polybar-msg cmd quit

# Launch bar
for m in $(polybar --list-monitors | cut -d":" -f1); do
    echo "---" | tee -a /tmp/polybar.log
    MONITOR=$m polybar --reload bar >>/tmp/polybar.log 2>&1 &
done
