#!/usr/bin/env sh

xrandr -q | grep -w connected | grep -q HDMI1 && xrandr --output eDP1 --dpi 112 --mode 1366x768 --rate 60.00 --pos 0x0 --primary --output HDMI1 --auto --right-of eDP1

# set cursor
xsetroot -xcf /usr/share/icons/Breeze_Obsidian/cursors/left_ptr 32

# set Xresources
[ -f $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources

# key binding
pgrep -x sxhkd && pkill -x sxhkd && sxhkd || sxhkd &
# restore wallpaper
nitrogen --restore &
# notify daemon
dunst -config ~/.config/dunst/dunstrc &
# transparency
picom -cCGb &
# bar
$HOME/.config/polybar/launch
